### ISSUE TITLE
Applying CSS class to embed code

### ISSUE THREAD

**Issue by iadj** [oscarotero/Embed#108]
A great feature would be the ability to add a CSS class into the embed code tags i.e.

`$embedconfig = ['adapter'=>['css'=>'myclass']];`
returns
`<iframe class='someclass'> ... `

**Comment by oscarotero** [comment]
This is not a good idea because two reasons:
* The code returned by some sites is a `<script>` element to create the `<iframe>` (twitter, facebook, etc)
* Some sites returns `<iframe>` but others `<video>`, `<object>`, `<embed>`, etc

The best way is insert the code inside a `<div class="someclass"></div>` and use descendant css selectors. Example:
```php
echo '<div class="embed-code">'.$info->code.'</div>';
```
```css
.embed-code iframe {
    /* your styles here */
}
```

Thanks anyway for the suggestion :smile:
