### ISSUE TITLE
FOLLOWLOCATION does not work with some php configurations

### ISSUE THREAD

**Issue by oscarotero** [oscarotero/Embed#120]
After an issue reported by @mwallisch seems like curl does not follow the redirect responses under some configurations related with `safe_mode` and `open_basedir`.
Here's more info:
http://stackoverflow.com/questions/14054652/getting-301-with-curl-despite-followlocation

**Comment by mwallisch** [comment]
Hey Oscar, thanks for your quick response and for creating this issue here.

I have absolutely no insight into curl, and I am still new to this library, so I am not sure what my debug-findings mean. 

However, within Embed\RequestResolvers\Curl I replaced ] + `$this->config);` on Line 138 with `]);` So essentially I tested how it would behave with $this->config set to an empty Array. And voila Curl followed the redirect and everything worked. So this issue seems to be about some curl OPTION confusion. Again, I don't really know much about it. But hopefully this gets someone with more insight started.

**Comment by oscarotero** [comment]
mmm, interesting.

This means some of the configuration values in https://github.com/oscarotero/Embed/blob/master/src/RequestResolvers/Curl.php#L17 makes this to fail.

**Comment by oscarotero** [comment]
After remove the `CURLOPT_SSL_VERIFYPEER` and `CURLOPT_SSL_VERIFYHOST` default options, seems to work fine. I have to ensure this does not causes collateral damage.

**Comment by oscarotero** [comment]
After some tests, I wasn't able to make this work in all environments. In some servers `CURLOPT_SSL_VERIFYHOST` must be disabled and in others enabled. So I leave the thinks as was before.
But now the exception contains more information so if you see an error related with SSL, maybe changing this settings fixes the problem.
