### ISSUE TITLE
Not an issue, have a question

### ISSUE THREAD

**Issue by khanof89** [oscarotero/Embed#173]
is there anyway I can get some  data of a web page say first paragraph ? e.g http://embed.ly/code?url=http%3A%2F%2Fiamshahrukh.com

**Comment by oscarotero** [comment]
It would be nice to have a way to get the page description from the html code when the "standard" ways (opengraph, twitter cards, meta elements) does not provide it. The hard part is know what is the most relevant part of the body. In your example, the description provided by embedly is a bit decontextualized because the text above is missing.
If you want to get the html to find this content by yourself, you can do it in this way:

```php
$info = Embed::create($url);

if (!$info->description) {
    //Returns a DOMDocument instance:
    $html = $info->getRequest()->getHtmlContent();

    $info->description = getDescriptionFromDom($html);
}
```

If you find a reliable way to get a description from the DOMDocument, I'd be willing to include it.

**Comment by khanof89** [comment]
Thanks :)
