### ISSUE TITLE
Author name

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#184]
Checking a website: http://www.inc.com/will-yakowicz/perfect-storm-regulations-could-cripple-marijuana-industry.html

Your scripts return @WillYakowicz

But i found the author name tag
`<meta property="article:author" content="Will Yakowicz" />`

A suggestion.
there's image and images, or providerIcon and providerIcons.

It would be interesting to have separate for RSS
feed: the first main feed RSS
and
feeds: the feeds array

Great script, the best one

**Comment by oscarotero** [comment]
For author, the twitterCards provider has more priority than html. Anyway I've implemented the authorUrl in twittercards, because if you know the username, you know the url.
And about the RSS, it's not so easy. If you're in a post, what rss do you like? the comments rss? the new posts?. I think this is hard to standarize.
