### ISSUE TITLE
Allow to define a namespace where to place custom adapters

### ISSUE THREAD

**Issue by oscarotero** [oscarotero/Embed#235]
This allows to customize the behaviour of this library easily.

**Comment by JanPetterMG** [comment]
I'll guess it will be easy to re-use most of the needed code to also place custom providers?
It's just an suggestion... (I don't need it)

**Comment by oscarotero** [comment]
Yes. This can be used to address #220. For example, creating a class extending the `Embed\Providers\Webpage` to change or disable some providers.

**Comment by JanPetterMG** [comment]
How about simplifying it even more?
Instead of making it harder to the end-user to make small adjustments, why don't we just use a config array similar to #220 ?

For example:
```php
$config['providers'] = [
    'OEmbed',
    'OpenGraph',
    '\\my\\custom\\namespace\\ArticleInfo',
    'Linkpulse',
    'TwitterCards',
];
```

Rules:
1. Unless empty, only providers in the config array are used.
2. The order of the list, is how providers is prioritized over each other.
3. Providers without namespace are expected to be Embed's own providers.
4. The name of the provider, is always it's class name.

How to fix it?
1. If `$config['providers']` isn't set, fallback to the list in the default config. (easy)
2. This fixes itself (no work needed)
3. Append Embed's `Providers` namespace for those without. Then constructing them all.
4. `strtolower( substr($class, strrpos($class, '\\')+2) )`

That's it, it's not complicated at all :)

**Comment by oscarotero** [comment]
The providers cannot be configured globally. There're many adapters with different providers. For example, [Archive](https://github.com/oscarotero/Embed/blob/master/src/Adapters/Archive.php#L31) prepends a provider to use the api of archive.org. [File](https://github.com/oscarotero/Embed/blob/master/src/Adapters/File.php#L54) uses just one provider because it handle binary files, so using providers relying in html tags makes no sense. And [Google](https://github.com/oscarotero/Embed/blob/master/src/Adapters/Google.php#L35) use the `GoogleMaps` provider only when is needed.

Instead create a set of new options to configure the internal behaviour of the adapters, it's more flexible and elegant to extend the adapters with your own code.
