### ISSUE TITLE
Type is misleading, it needs to change

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#236]
`Provider->getType()` always returns a predefined value `video`|`photo`|`link`|`rich`|`video`.
Why does it have to be that way? Why do we need to use `$provider->bag->get('property')` to get the correct value?
It's already discussed a little bit in #205, but how about change to the better?

I'm currently working on new providers, as well as extending the `Adapter` with more easily accessible data. For one of those providers, `article-info`, it makes no sense to return `link` in case of eg. `story`, `interview`, `guide` or `review`.

Option A:
New `Adapter->getMediaType()` to return a high-level `Embed`-predefined value.

Option B:
New optional parameter `Adapter->getType($highlevel=false)`, set to `true` only when a `Embed`-predefined type is wanted.

Any thoughts about this?

**Comment by oscarotero** [comment]
The type is created for presentation purposed, allowing to use different layouts depending of the type of link. For example, *link* means no embed code is returned. This was a requirement when I created this library (like the aspect ratio, to allow to insert the widgets responsively). This removes also many cases in which different providers return different values. Example: one provider returns *rich* an other *video*. Or there can be many cases in which all providers return nothing but there's an embed code.

So, the problem is not only provide the original value of the providers, but also handle all these cases in which we have different values or no values at all.

I think with the new `custom_adapters_namespace` you can implement your own needs, and if you think there's something interesting for the community (new providers, or new standard values that the providers can returns), create a pull request, and I'll be happy to accept.

**Comment by JanPetterMG** [comment]
So even option B isn't good enough?

I fully understand your arguments, but to not allow fetching the original value at all, unless specifying a provider-specific property name, is just nuts! Most providers are just using 'type' as property name, I get that, but that's not the case everywhere.

I'm NOT asking for removal, just native support to fetch the original value!

If this is Embeds politics, then I'm going to run run a separate parallell fork of Embed, as I'm not interested in replacing every single provider with a slightly changed duplicate.

**Comment by JanPetterMG** [comment]
Expect an PR soon, I'll try to make the best of both worlds. If you don't like it, just close it.

**Comment by oscarotero** [comment]
I don't want to return different values depending of a configuration. Makes the value not reliable. The only solution is create a new property to return that. For example:

```php
$info->type; // link
$info->fullType; // article:story
```

Any other better name is welcome.

**Comment by JanPetterMG** [comment]
If I'm allowed to ask:

Why do we have both `$info->getType()` and a public `$info->type` property?
A function and a property bag should be more than enough, but now there is 3 different ways to fetch data!

**Comment by oscarotero** [comment]
`$info->type` is a magic property that executes and cache the result of `$info->getType()` [here](https://github.com/oscarotero/Embed/blob/master/src/Adapters/Adapter.php#L88)
This prevent to execute expensive operations more than once.

**Comment by JanPetterMG** [comment]
Yeah, I get that, but why not using it as internal cache only, and why not as a array?
Because of this we're required to have multiple functions/properties instead of using the flexibility of a function... just saying.

**Comment by oscarotero** [comment]
I'm not sure what do you mean. The functions should not be used publicly, they are used only by the magic method. In fact, maybe they should be protected, instead public.
This way is easier because some properties use other properties to calculate its value. For example: https://github.com/oscarotero/Embed/blob/master/src/Adapters/Adapter.php#L455 or https://github.com/oscarotero/Embed/blob/master/src/Adapters/Adapter.php#L546
