### ISSUE TITLE
Why did you remove `images` in version 4 ? 

### ISSUE THREAD

**Issue by nicolas-t** [oscarotero/Embed#343]
Hello,

I've seen here that you removed the `images` array :
https://github.com/oscarotero/Embed/blob/v4.0.0/CHANGELOG.md

Why did you choose to do so ?

Thanks

**Comment by oscarotero** [comment]
Many reasons:

- It was a very opinionated value, with a lot of settings, so it's hard to work with: get the bigger image first, ignore images with a specific pattern, get only images from the same domain, etc. 
- It was expensive, because performs a http request for each image (and this can lead to dozens of requests).
- To avoid load the fully image content, the http request should load only the minimum data required to get the format and size, and then stop the transition. And this is a very specific behavior that cannot be done only with PSR-18 interface.
- The `image` value depended on `images`, so even if you only wanted the "standard" image, the library would send all those http requests anyway.
- Embed 4 allows to add custom values, so if you want to restore this functionality, just create a detector for that, which works exactly as you want:

```php
$embed->getExtractorFactory()->addDetector('images', Images::class);
```

**Comment by nicolas-t** [comment]
Makes sense, thanks !
