### ISSUE TITLE
Description character count limited?

### ISSUE THREAD

**Issue by danvolkens** [oscarotero/Embed#353]
It seems that description is char-limited to 246 or so. Is that intentional? If it is, we'll make sure to adjust our descriptions to accommodate. Here's an example: https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.buzzsprout.com%2F108830%2F2249300-ventilation-oxygenation-and-perfusion

Tks!

**Comment by oscarotero** [comment]
This library does not manipulate the description, only returns its value as is. In your example, you can see the document has three descriptions: `og:description`, `twitter:description` and `description`, the first one is cropped and this is the one choosed by the code (https://github.com/oscarotero/Embed/blob/master/src/Detectors/Description.php#L15) because it has more priority.

**Comment by danvolkens** [comment]
Ahh, gotcha. Thank you for the clarification! That is no problem. We'll accommodate on our side based on understanding that priority. Tks!
