### ISSUE TITLE
How to detect type.

### ISSUE THREAD

**Issue by vimalmistry** [oscarotero/Embed#422]
I want to detect type of url. like is it photo or video

My use case is. I want to allow url which are only videos and gif. I want to reject request on any else url. I think once I used old version. there was option of type. But I can not find on new version. 

Thank you

**Comment by oscarotero** [comment]
Type was removed in the latest version because it wan't a reliable value. Sites that have oEmbed can return it, but others don't so we have to make several checks in order to guess "magically" the type of content.

If you need to recover this, you can create your own detector, following the instructions here: https://github.com/oscarotero/Embed#detectors

**Comment by garbinmarcelo** [comment]
@vimalmistry Did you make it? I also need something similar.

**Comment by vimalmistry** [comment]
@garbinmarcelo No. I just using older version of this repo. But still searching solution for this.
