### ISSUE TITLE
Support PHP 7

### ISSUE THREAD

**Issue by mburtscher** [oscarotero/Embed#82]
Library should support __and test__ PHP 7.

Currently PHP 7 is defined as allowed failure in Travis. I think this is required since PHPUnit 4 is used which is not compatible with PHP 7. On the other hand PHPUnit 5 does not support any PHP version below 5.6.

I'd suggest releasing a new major version 3.0 when PHP 7 is stable and dropping support for everything below 5.6.

**Comment by oscarotero** [comment]
I'd like to drop support for old php versions only if I need any feature not available in these versions. For example, 2.0 does not support PHP 5.3 because [getimagesizefromstring](http://php.net/getimagesizefromstring) (used to get the image dimmensions). Currently, there are a lot of people using php < 5.6, and do not support these versions only because phpunit, is a bit unreasonable.
Maybe there's a way to test the library with both phpunit versions?

**Comment by younes0** [comment]
You could check with https://github.com/sstalle/php7cc first

**Comment by oscarotero** [comment]
Oh, I will do. Thanks!

**Comment by mburtscher** [comment]
You're totally right that dropping support for PHP 5.5 __just for testing reasons__ is not the best practice. In our private projects we use Codeship where we can load the PHPUnit PHAR version and run different commands for different PHP versions.

I don't have much experience with Travis CI so I don't know what's possible. We could write a setup-script that loads either PHPUnit 4/5 based on the currently selected PHP environment. Then execute tests using `php phpunit.phar` instead of `vendor/bin/phpunit`.

**Comment by oscarotero** [comment]
Travis has phpunit installed globally by default. Some time ago, I decided to use the phpunit installed with composer instead the provided by travis, because a bug. But now it's working fine, so, I've changed again to use the Travis' phpunit that is 4.8.x for PHP 5.x and 5 for PHP 7. So now it's tested correctly in php5 and php7.

**Comment by lipsmega** [comment]
Hi friends, I got an error with php 7.0, but dont know why :(
