### ISSUE TITLE
move maxImages option to ImageInfo

### ISSUE THREAD

**Issue by younes0** [oscarotero/Embed#83]
It seems that only html provider has `maxImages` option. 
We could add `maxImages` to all providers and snce this option makes sense when it comes to limit images downloading, so why not adding directly to ImageInfo classes?

**Comment by younes0** [comment]
Okay so I didn't know that getImagesUrl() existed and it doesn't fetch images unlike ->image()
This issue may be irrelevant now since I can directly handle the images fetching.

**Comment by oscarotero** [comment]
maxImages is used only in html because this provider get all images found indiscriminately in the html, and there's some pages with a lot of images. Other providers (oembed, opengraph, twittercard, etc) return only one or two images each, and they are relevant, so this option is not necessary.
`getImagesUrls()` collects and filter all images from all providers, but doesn't get the dimmensions or mimetype. It's useful if you just want the urls found.

**Comment by younes0** [comment]
Thanks for the explanations
